stages:
  - test

tests:
  stage: test
  resource_group: e2e-stand-requests
  image: mcr.microsoft.com/playwright/python:v1.40.0-jammy
  script:
    - echo Using public URL $PUBLIC_URL
    - pip install -r requirements.txt --default-timeout=100 
    - pytest -sv

