stages:
  - test
  - report

tests:
  stage: test
  resource_group: e2e-stand-requests
  image: mcr.microsoft.com/playwright/python:v1.43.0-jammy
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - allure-report
  before_script:
    - apt update && apt install -y openjdk-17-jdk openjdk-17-jre
    - apt-get install wget
    - wget https://github.com/allure-framework/allure2/releases/download/2.28.0/allure-2.28.0.tgz && tar -zxvf allure-2.28.0.tgz -C /opt/ && ln -s /opt/allure-2.28.0/bin/allure /usr/bin/allure
  script:
    - echo Using public URL $PUBLIC_URL
    - pip install -r requirements.txt --default-timeout=100 
    - pytest --reruns=${RERUNS_NUMBER} --alluredir=allure-results
  after_script:
    - if [ $CI_JOB_STATUS == 'failed' ]; then curl -s -X POST -d "chat_id=${TELEGRAM_CHAT_ID}&text=' !!! E2E tests failed !!! '&parse_mode=Markdown" "https://api.telegram.org/bot${TELEGRAM_API_TOKEN}/sendMessage"; fi


pages:
    stage: report
    needs:
        - run_tests
    script:
        - mkdir public
        - cp -r allure-report/* public
    artifacts:
        when: on_success
        expire_in: never
        paths:
            - public
